#ifndef NANOUSD_TYPES_H
#define NANOUSD_TYPES_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#define NANOUSD_API


#ifdef __cplusplus
extern "C" {
#endif

enum nusd_result_e {
    NUSD_RESULT_OK = 0,
    NUSD_RESULT_INVALID_ATTRIBUTE_PATH,
    NUSD_RESULT_INVALID_RELATIONSHIP_PATH,
    NUSD_RESULT_INVALID_PRIM_PATH,
    NUSD_RESULT_WRONG_TYPE,
    NUSD_RESULT_CREATE_STAGE_FAILED,
    NUSD_RESULT_OPEN_STAGE_FAILED,
    NUSD_RESULT_DEFINE_PRIM_FAILED,
    NUSD_RESULT_INVALID_PROPERTY_PATH,
    NUSD_RESULT_INVALID_PROPERTY_TYPE,
    NUSD_RESULT_CREATE_RELATIONSHIP_FAILED,
    NUSD_RESULT_CREATE_ATTRIBUTE_FAILED,
    NUSD_RESULT_NULL_PARAMETER,
    NUSD_RESULT_CONNECTION_FAILED,
    NUSD_RESULT_INVALID_SHADER_INPUT,
    NUSD_RESULT_INVALID_SHADER_OUTPUT,
    NUSD_RESULT_CREATE_INPUT_FAILED,
    NUSD_RESULT_CREATE_OUTPUT_FAILED,
    NUSD_RESULT_INVALID_MATERIAL_PATH,
    NUSD_RESULT_APPLY_BINDING_API_FAILED,
    NUSD_RESULT_CREATE_BINDING_FAILED,
    NUSD_RESULT_SET_METADATA_FAILED,
    NUSD_RESULT_INVALID_SUBDIVISION_SCHEME,
    NUSD_RESULT_INVALID_TRIANGLE_SUBDIVISION_RULE,
    NUSD_RESULT_INVALID_INTERPOLATION,
    NUSD_RESULT_INVALID_UP_AXIS,
};
typedef int nusd_result_t;

typedef char const* nusd_colorspace_t;
typedef void* nusd_stage_t;
typedef struct nusd_asset_path_s* nusd_asset_path_t;
typedef struct nusd_string_s* nusd_string_t;

enum nusd_type_e {
    NUSD_TYPE_ASSET,
    NUSD_TYPE_ASSETARRAY,
    NUSD_TYPE_BOOL,
    NUSD_TYPE_BOOLARRAY,
    NUSD_TYPE_COLOR3D,
    NUSD_TYPE_COLOR3DARRAY,
    NUSD_TYPE_COLOR3F,
    NUSD_TYPE_COLOR3FARRAY,
    NUSD_TYPE_COLOR3H,
    NUSD_TYPE_COLOR3HARRAY,
    NUSD_TYPE_COLOR4D,
    NUSD_TYPE_COLOR4DARRAY,
    NUSD_TYPE_COLOR4F,
    NUSD_TYPE_COLOR4FARRAY,
    NUSD_TYPE_COLOR4H,
    NUSD_TYPE_COLOR4HARRAY,
    NUSD_TYPE_DOUBLE,
    NUSD_TYPE_DOUBLE2,
    NUSD_TYPE_DOUBLE2ARRAY,
    NUSD_TYPE_DOUBLE3,
    NUSD_TYPE_DOUBLE3ARRAY,
    NUSD_TYPE_DOUBLE4,
    NUSD_TYPE_DOUBLE4ARRAY,
    NUSD_TYPE_DOUBLEARRAY,
    NUSD_TYPE_FIND,
    NUSD_TYPE_FLOAT,
    NUSD_TYPE_FLOAT2,
    NUSD_TYPE_FLOAT2ARRAY,
    NUSD_TYPE_FLOAT3,
    NUSD_TYPE_FLOAT3ARRAY,
    NUSD_TYPE_FLOAT4,
    NUSD_TYPE_FLOAT4ARRAY,
    NUSD_TYPE_FLOATARRAY,
    NUSD_TYPE_FRAME4D,
    NUSD_TYPE_FRAME4DARRAY,
    NUSD_TYPE_GROUP,
    NUSD_TYPE_HALF,
    NUSD_TYPE_HALF2,
    NUSD_TYPE_HALF2ARRAY,
    NUSD_TYPE_HALF3,
    NUSD_TYPE_HALF3ARRAY,
    NUSD_TYPE_HALF4,
    NUSD_TYPE_HALF4ARRAY,
    NUSD_TYPE_HALFARRAY,
    NUSD_TYPE_INT,
    NUSD_TYPE_INT2,
    NUSD_TYPE_INT2ARRAY,
    NUSD_TYPE_INT3,
    NUSD_TYPE_INT3ARRAY,
    NUSD_TYPE_INT4,
    NUSD_TYPE_INT4ARRAY,
    NUSD_TYPE_INT64,
    NUSD_TYPE_INT64ARRAY,
    NUSD_TYPE_INTARRAY,
    NUSD_TYPE_MATRIX2D,
    NUSD_TYPE_MATRIX2DARRAY,
    NUSD_TYPE_MATRIX3D,
    NUSD_TYPE_MATRIX3DARRAY,
    NUSD_TYPE_MATRIX4D,
    NUSD_TYPE_MATRIX4DARRAY,
    NUSD_TYPE_NORMAL3D,
    NUSD_TYPE_NORMAL3DARRAY,
    NUSD_TYPE_NORMAL3F,
    NUSD_TYPE_NORMAL3FARRAY,
    NUSD_TYPE_NORMAL3H,
    NUSD_TYPE_NORMAL3HARRAY,
    NUSD_TYPE_OPAQUE,
    NUSD_TYPE_PATHEXPRESSION,
    NUSD_TYPE_PATHEXPRESSIONARRAY,
    NUSD_TYPE_POINT3D,
    NUSD_TYPE_POINT3DARRAY,
    NUSD_TYPE_POINT3F,
    NUSD_TYPE_POINT3FARRAY,
    NUSD_TYPE_POINT3H,
    NUSD_TYPE_POINT3HARRAY,
    NUSD_TYPE_QUATD,
    NUSD_TYPE_QUATDARRAY,
    NUSD_TYPE_QUATF,
    NUSD_TYPE_QUATFARRAY,
    NUSD_TYPE_QUATH,
    NUSD_TYPE_QUATHARRAY,
    NUSD_TYPE_STRING,
    NUSD_TYPE_STRINGARRAY,
    NUSD_TYPE_TEXCOORD2D,
    NUSD_TYPE_TEXCOORD2DARRAY,
    NUSD_TYPE_TEXCOORD2F,
    NUSD_TYPE_TEXCOORD2FARRAY,
    NUSD_TYPE_TEXCOORD2H,
    NUSD_TYPE_TEXCOORD2HARRAY,
    NUSD_TYPE_TEXCOORD3D,
    NUSD_TYPE_TEXCOORD3DARRAY,
    NUSD_TYPE_TEXCOORD3F,
    NUSD_TYPE_TEXCOORD3FARRAY,
    NUSD_TYPE_TEXCOORD3H,
    NUSD_TYPE_TEXCOORD3HARRAY,
    NUSD_TYPE_TIMECODE,
    NUSD_TYPE_TIMECODEARRAY,
    NUSD_TYPE_TOKEN,
    NUSD_TYPE_TOKENARRAY,
    NUSD_TYPE_UCHAR,
    NUSD_TYPE_UCHARARRAY,
    NUSD_TYPE_UINT,
    NUSD_TYPE_UINT64,
    NUSD_TYPE_UINT64ARRAY,
    NUSD_TYPE_UINTARRAY,
    NUSD_TYPE_VECTOR3D,
    NUSD_TYPE_VECTOR3DARRAY,
    NUSD_TYPE_VECTOR3F,
    NUSD_TYPE_VECTOR3FARRAY,
    NUSD_TYPE_VECTOR3H,
    NUSD_TYPE_VECTOR3HARRAY,
    NUSD_TYPE_RELATIONSHIP
};
typedef int nusd_type_t;

/// Converts a nusd_type_t to a string.
/// @param type The nusd_type_t to convert.
/// @return A string representation of the nusd_type_t. "INVALID" if the type is not valid.
NANOUSD_API 
char const* nusd_type_to_string(nusd_type_t type);


extern nusd_colorspace_t NUSD_COLORSPACE_LINEAR_AP1;
extern nusd_colorspace_t NUSD_COLORSPACE_LINEAR_AP0;
extern nusd_colorspace_t NUSD_COLORSPACE_LINEAR_REC709;
extern nusd_colorspace_t NUSD_COLORSPACE_LINEAR_P3D65;
extern nusd_colorspace_t NUSD_COLORSPACE_LINEAR_REC2020;
extern nusd_colorspace_t NUSD_COLORSPACE_LINEAR_ADOBERGB;
extern nusd_colorspace_t NUSD_COLORSPACE_LINEAR_CIEXYZD65;
extern nusd_colorspace_t NUSD_COLORSPACE_LINEAR_DISPLAYP3;
extern nusd_colorspace_t NUSD_COLORSPACE_SRGB_REC709;
extern nusd_colorspace_t NUSD_COLORSPACE_G22_REC709;
extern nusd_colorspace_t NUSD_COLORSPACE_G18_REC709;
extern nusd_colorspace_t NUSD_COLORSPACE_SRGB_AP1;
extern nusd_colorspace_t NUSD_COLORSPACE_G22_AP1;
extern nusd_colorspace_t NUSD_COLORSPACE_G22_ADOBERGB;
extern nusd_colorspace_t NUSD_COLORSPACE_IDENTITY;
extern nusd_colorspace_t NUSD_COLORSPACE_DATA;
extern nusd_colorspace_t NUSD_COLORSPACE_RAW;
extern nusd_colorspace_t NUSD_COLORSPACE_SRGB;
extern nusd_colorspace_t NUSD_COLORSPACE_UNKNOWN;
extern nusd_colorspace_t NUSD_COLORSPACE_CIEXYZ;

extern double NUSD_TIMECODE_DEFAULT;

/// Up axis values for stage metadata.
/// @see nusd_stage_set_up_axis()
/// @see nusd_stage_get_up_axis()
enum nusd_up_axis_e {
    NUSD_UP_AXIS_Y = 0, ///< Y-axis is up (default for many applications)
    NUSD_UP_AXIS_Z = 1, ///< Z-axis is up (common in CAD and some game engines)
};
typedef int nusd_up_axis_t;

#define NUSD_UNIT_METERS 1.0
#define NUSD_UNIT_DECIMETERS 0.1
#define NUSD_UNIT_CENTIMETERS 0.01

#ifdef __cplusplus
}
#endif

#endif